module.exports = {
  STATUS_BAD_REQUEST: 400,
  STATUS_UNAUTHORIZED: 401,
  STATUS_FORBIDDEN: 403,
  STATUS_NOT_FOUND: 404,
  STATUS_CONFLICT: 409,
  STATUS_SERVER_ERROR: 500,

  MSG_SERVER_ERROR: 'An error occurred on the server',
};
